---

- name: "01.1 - make sure kubernetes directories exist"
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ __control_plane_user }}"
    group: "{{ __control_plane_group }}"
    mode: "ug=rwX,o-rwx"
  become: yes
  loop:
    - "{{ __control_plane_config_dir }}"
    - "{{ __control_plane_pki_dir }}"
    - "{{ __control_plane_manifests_dir }}"
    - "{{ __control_plane_data_dir }}"
