---

- name: "02.1 - download kubernetes binaries"
  get_url:
    url: "{{ item }}"
    dest: "{{ __control_plane_play_dir }}/{{ item | urlsplit('path') | basename }}"
  loop:
    - "{{ __control_plane_kubectl_download_url }}"
    - "{{ __control_plane_kube_apiserver_download_url }}"

- name: "02.2 - install kubernetes binaries"
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    remote_src: yes
    owner: "{{ __control_plane_user }}"
    group: "{{ __control_plane_group }}"
    mode: "0755"
  become: yes
  loop:
    - src: "{{ __control_plane_play_dir }}/{{ __control_plane_kubectl_download_url | urlsplit('path') | basename }}"
      dest: "{{ __control_plane_kubectl_binary }}"
    - src: "{{ __control_plane_play_dir }}/{{ __control_plane_kube_apiserver_download_url | urlsplit('path') | basename }}"
      dest: "{{ __control_plane_kube_apiserver_binary }}"
