---

- name: "03.1 - place all the pki data into appropriate place"
  copy:
    content: "{{ item.content }}"
    dest: "{{ item.dest }}"
    owner: "{{ __control_plane_user }}"
    group: "{{ __control_plane_group }}"
    mode: "ug=rwX,o-rwx"
  become: yes
  loop_control:
    label: "{{ item.dest }}"
  loop:
    - content: "{{ control_plane_ca_cert }}"
      dest: "{{ __control_plane_pki_ca_cert_file }}"
    - content: "{{ control_plane_ca_key }}"
      dest: "{{ __control_plane_pki_ca_key_file }}"
    - content: "{{ control_plane_api_server_cert }}"
      dest: "{{ __control_plane_pki_api_server_cert_file }}"
    - content: "{{ control_plane_api_server_key }}"
      dest: "{{ __control_plane_pki_api_server_key_file }}"
    - content: "{{ control_plane_service_account_cert }}"
      dest: "{{ __control_plane_pki_service_account_cert_file }}"
    - content: "{{ control_plane_service_account_key }}"
      dest: "{{ __control_plane_pki_service_account_key_file }}"
    - content: "{{ control_plane_admin_user_cert }}"
      dest: "{{ __control_plane_pki_admin_user_cert_file }}"
    - content: "{{ control_plane_admin_user_key }}"
      dest: "{{ __control_plane_pki_admin_user_key_file }}"
    - content: "{{ control_plane_kube_controller_manager_cert }}"
      dest: "{{ __control_plane_pki_kube_controller_manager_cert_file }}"
    - content: "{{ control_plane_kube_controller_manager_key }}"
      dest: "{{ __control_plane_pki_kube_controller_manager_key_file }}"
    - content: "{{ control_plane_kube_scheduler_cert }}"
      dest: "{{ __control_plane_pki_kube_scheduler_cert_file }}"
    - content: "{{ control_plane_kube_scheduler_key }}"
      dest: "{{ __control_plane_pki_kube_scheduler_key_file }}"

- name: "03.2 - template authentication manifests"
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ __control_plane_user }}"
    group: "{{ __control_plane_group }}"
  become: yes
  loop_control:
    label: "{{ item.dest }}"
  loop:
    - src: admin-user.tpl.kubeconfig
      dest: "{{ __control_plane_admin_user_kubeconfig_file }}"
    - src: kube-controller-manager.tpl.kubeconfig
      dest: "{{ __control_plane_kube_controller_manager_kubeconfig_file }}"
    - src: kube-scheduler.tpl.kubeconfig
      dest: "{{ __control_plane_kube_scheduler_kubeconfig_file }}"
