---

- name: "03.1 - place all the pki data into appropriate place"
  copy:
    content: "{{ item.content }}"
    dest: "{{ item.dest }}"
    owner: "{{ __control_plane_user }}"
    group: "{{ __control_plane_group }}"
    mode: "ug=rwX,o-rwx"
  become: yes
  loop_control:
    label: "{{ item.dest }}"
  loop:
      # etcd-ca
    - content: "{{ control_plane_etcd_ca_cert }}"
      dest: "{{ __control_plane_etcd_ca_cert_file }}"
      # kubernetes-ca
    - content: "{{ control_plane_kubernetes_ca_cert }}"
      dest: "{{ __control_plane_kubernetes_ca_cert_file }}"
    - content: "{{ control_plane_kubernetes_ca_key }}"
      dest: "{{ __control_plane_kubernetes_ca_key_file }}"
      # service account
    - content: "{{ control_plane_service_account_pub }}"
      dest: "{{ __control_plane_service_account_pub_file }}"
    - content: "{{ control_plane_service_account_key }}"
      dest: "{{ __control_plane_service_account_key_file }}"
      # kube-apiserver
    - content: "{{ control_plane_kube_apiserver_cert }}"
      dest: "{{ __control_plane_kube_apiserver_cert_file }}"
    - content: "{{ control_plane_kube_apiserver_key }}"
      dest: "{{ __control_plane_kube_apiserver_key_file }}"
      # kube-apiserver-etcd-client
    - content: "{{ control_plane_kube_apiserver_etcd_client_cert }}"
      dest: "{{ __control_plane_kube_apiserver_etcd_client_cert_file }}"
    - content: "{{ control_plane_kube_apiserver_etcd_client_key }}"
      dest: "{{ __control_plane_kube_apiserver_etcd_client_key_file }}"
      # kube-apiserver-kubelet-client
    - content: "{{ control_plane_kube_apiserver_kubelet_client_cert }}"
      dest: "{{ __control_plane_kube_apiserver_kubelet_client_cert_file }}"
    - content: "{{ control_plane_kube_apiserver_kubelet_client_key }}"
      dest: "{{ __control_plane_kube_apiserver_kubelet_client_key_file }}"
      # admin
    - content: "{{ control_plane_admin_user_cert }}"
      dest: "{{ __control_plane_admin_user_cert_file }}"
    - content: "{{ control_plane_admin_user_key }}"
      dest: "{{ __control_plane_admin_user_key_file }}"
      # kube-controller-manager
    - content: "{{ control_plane_kube_controller_manager_cert }}"
      dest: "{{ __control_plane_kube_controller_manager_cert_file }}"
    - content: "{{ control_plane_kube_controller_manager_key }}"
      dest: "{{ __control_plane_kube_controller_manager_key_file }}"
      # kube-scheduler
    - content: "{{ control_plane_kube_scheduler_cert }}"
      dest: "{{ __control_plane_kube_scheduler_cert_file }}"
    - content: "{{ control_plane_kube_scheduler_key }}"
      dest: "{{ __control_plane_kube_scheduler_key_file }}"
      # front-proxy
    - content: "{{ control_plane_front_proxy_ca_cert }}"
      dest: "{{ __control_plane_front_proxy_ca_cert_file }}"
    - content: "{{ control_plane_front_proxy_client_cert }}"
      dest: "{{ __control_plane_front_proxy_client_cert_file }}"
    - content: "{{ control_plane_front_proxy_client_key }}"
      dest: "{{ __control_plane_front_proxy_client_key_file }}"

- name: "03.2 - template Admin user authentication manifest"
  template:
    src: admin-user.kubeconfig.yaml
    dest: "{{ __control_plane_admin_user_kubeconfig_file }}"
    owner: "{{ __control_plane_user }}"
    group: "{{ __control_plane_group }}"
  become: yes
