---

- name: "03.1 - place all the pki data into appropriate place"
  copy:
    content: "{{ item.content }}"
    dest: "{{ item.dest }}"
    owner: "{{ __control_plane_user }}"
    group: "{{ __control_plane_group }}"
    mode: "ug=rwX,o-rwx"
  become: yes
  loop_control:
    label: "{{ item.dest | basename }}"
  loop:
    - content: "{{ control_plane_ca_cert }}"
      dest: "{{ __control_plane_pki_ca_cert }}"
    - content: "{{ control_plane_ca_key }}"
      dest: "{{ __control_plane_pki_ca_key }}"
    - content: "{{ control_plane_api_server_cert }}"
      dest: "{{ __control_plane_pki_api_server_cert }}"
    - content: "{{ control_plane_api_server_key }}"
      dest: "{{ __control_plane_pki_api_server_key }}"
    - content: "{{ control_plane_service_account_cert }}"
      dest: "{{ __control_plane_pki_service_account_cert }}"
    - content: "{{ control_plane_service_account_key }}"
      dest: "{{ __control_plane_pki_service_account_key }}"
    - content: "{{ control_plane_admin_user_cert }}"
      dest: "{{ __control_plane_pki_admin_user_cert }}"
    - content: "{{ control_plane_admin_user_key }}"
      dest: "{{ __control_plane_pki_admin_user_key }}"
    - content: "{{ control_plane_kube_controller_manager_cert }}"
      dest: "{{ __control_plane_kube_controller_manager_cert }}"
    - content: "{{ control_plane_kube_controller_manager_key }}"
      dest: "{{ __control_plane_kube_controller_manager_key }}"
    - content: "{{ control_plane_kube_scheduler_cert }}"
      dest: "{{ __control_plane_kube_scheduler_cert }}"
    - content: "{{ control_plane_kube_scheduler_key }}"
      dest: "{{ __control_plane_kube_scheduler_key }}"

- name: "03.2 - template authentication manifests"
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ __control_plane_user }}"
    group: "{{ __control_plane_group }}"
  become: yes
  loop_control:
    label: "{{ item.dest | basename }}"
  loop:
    - src: admin-user.tpl.yaml
      dest: "{{ __control_plane_manifests_admin_user_config }}"
    - src: kube-controller-manager.tpl.yaml
      dest: "{{ __control_plane_manifests_kube_controller_manager_config }}"
    - src: kube-scheduler.tpl.yaml
      dest: "{{ __control_plane_manifests_kube_scheduler_config }}"
