---

# assume etcd cluster is deployed on the same master nodes as Kubernetes API service
- name: "05.1 - set variable combining ips of etcd cluster nodes"
  set_fact:
    # we need to get a string value, like:
    #   "https://10.0.0.1:2380,https://10.0.0.2:2380"
    _etcd_cluster_nodes: "{{ _etcd_cluster_nodes|default('') + 'https://' + item + ':' + __control_plane_etcd_listen_client_port|string + (ansible_loop.last | ternary('', ',')) }}"
  loop: "{{ control_plane_kubernetes_cluster_master_ips.split(',') }}"
  loop_control:
    extended: yes

- name: "05.2 - template Kubernetes API unit-file"
  template:
    src: kube-apiserver.tpl.service
    dest: "{{ __control_plane_kube_apiserver_systemd_unit_file }}"
  become: yes
  notify:
    - control-plane-reload-systemd
    - control-plane-restart-kube-apiserver-service

- meta: flush_handlers

- name: "05.3 - make sure Kubernetes API service is started"
  service:
    name: "{{ __control_plane_kube_apiserver_service }}"
    state: started
    enabled: yes
  become: yes
