---

- name: "06.1 - template Kubernetes Controller Manager unit-file"
  template:
    src: kube-controller-manager.service
    dest: "{{ __control_plane_kube_controller_manager_systemd_unit_file }}"
  become: yes
  notify:
    - control-plane-reload-systemd
    - control-plane-restart-kube-controller-manager-service

- meta: flush_handlers

- name: "06.2 - make sure Kubernetes Controller Manager is started"
  service:
    name: "{{ __control_plane_kube_controller_manager_service }}"
    state: started
    enabled: yes
  become: yes
