---

#- name: "06.2 - make sure kube-controller-manager Pod is started"
#  k8s:
#    apply: yes
#    kubeconfig: "{{ __control_plane_admin_user_kubeconfig_file }}"
#    src: "{{ __control_plane_manifests_kube_controller_manager_pod_file }}"
#    state: present
#    wait: yes
#  become: yes

- name: "06.1 - template Kubernetes Controller Manager unit-file"
  template:
    src: kube-controller-manager.tpl.service
    dest: "{{ __control_plane_kube_controller_manager_systemd_unit_file }}"
  become: yes
  notify:
    - control-plane-reload-systemd
    - control-plane-restart-kube-controller-manager-service

- meta: flush_handlers

- name: "06.2 - make sure Kubernetes Controller Manager is started"
  service:
    name: "{{ __control_plane_kube_controller_manager_service }}"
    state: started
    enabled: yes
  become: yes
