---

- name: "06.1 - run kube-controller-manager Pod after templating manifest"
  k8s:
    kubeconfig: "{{ __control_plane_manifests_admin_user_kubeconfig_file }}"
    definition: "{{ lookup('template', 'pod.kube-controller-manager.yaml') }}"
    state: present
    wait: yes
  become: yes

