---

# Deploy the DNS add-on which provides DNS based service discovery, backed by CoreDNS (https://coredns.io/), to
# applications running inside the Kubernetes cluster.

- name: "09.1 - wait until at least one node is ready"
  shell:
    cmd: "{{ __control_plane_kubectl_binary }} --kubeconfig={{ __control_plane_admin_user_kubeconfig_file }} get nodes 2>&1"
  args:
    warn: no
  environment:
    DEBIAN_FRONTEND: noninteractive
  become: yes
  changed_when: no
  register: _nodes
  until:
    - "'Ready' in _nodes.stdout"
  retries: 30
  delay: "{{ 60 | random(start=10, step=5, seed=inventory_hostname) }}"

- name: "09.2 - check if CoreDNS manifest is present"
  stat:
    path: "{{ __control_plane_manifests_dir }}/coredns.yaml"
    get_attributes: no
    get_checksum: no
    get_mime: no
  become: yes
  register: _coredns_manifest_file

- name: "09.3 - template CoreDNS manifest"
  template:
    src: coredns.yaml
    dest: "{{ __control_plane_manifests_dir }}/coredns.yaml"
  become: yes

- name: "09.4 - apply CoreDNS Deployment"
  k8s:
    kubeconfig: "{{ __control_plane_admin_user_kubeconfig_file }}"
    src: "{{ __control_plane_manifests_dir }}/coredns.yaml"
    apply: "{{ True if (_coredns_manifest_file.stat.exists is defined and _coredns_manifest_file.stat.exists) else False }}"
    state: present
  become: yes
