---

- include_tasks: 01-prepare-env.yaml

- include_tasks: 02-install-packages.yaml

- include_tasks: 03-configure-authentication.yaml

- include_tasks: 04-configure-encryption.yaml

- include_tasks: 05-setup-kube-apiserver.yaml

- include_tasks: 06-setup-kube-controller-manager.yaml

- include_tasks: 07-setup-kube-scheduler.yaml
