---

- name: "control-plane-reload-systemd"
  shell:
    cmd: "systemctl daemon-reload"
  args:
    warn: no
  environment:
    DEBIAN_FRONTEND: noninteractive
  become: yes

- name: "control-plane-restart-kube-apiserver-service"
  service:
    name: "{{ __control_plane_kube_apiserver_service }}"
    state: restarted
    enabled: yes
  become: yes
