---

- name: "control-plane-reload-systemd"
  shell:
    cmd: "systemctl daemon-reload"
  args:
    warn: no
  environment:
    DEBIAN_FRONTEND: noninteractive
  become: yes

- name: "control-plane-restart-kube-apiserver-service"
  service:
    name: "{{ __control_plane_kube_apiserver_service }}"
    state: restarted
    enabled: yes
  become: yes

- name: "control-plane-wait-kube-apiserver-service"
  pause:
    minutes: 3

- name: "control-plane-restart-kube-controller-manager-service"
  service:
    name: "{{ __control_plane_kube_controller_manager_service }}"
    state: restarted
    enabled: yes
  become: yes

- name: "control-plane-restart-kube-scheduler-service"
  service:
    name: "{{ __control_plane_kube_scheduler_service }}"
    state: restarted
    enabled: yes
  become: yes

- name: "control-plane-restart-kube-proxy-service"
  service:
    name: "{{ __control_plane_kube_proxy_service }}"
    state: restarted
    enabled: yes
  become: yes
