#jinja2: lstrip_blocks: True, trim_blocks: True
---
apiVersion: v1
kind: Config
clusters:
  - name: "{{ control_plane_kubernetes_cluster_name }}"
    cluster:
      server: "{{ control_plane_api_internal_endpoint }}"
      certificate-authority-data: {{ control_plane_ca_cert | string | b64encode }}
contexts:
  - name: default
    context:
      cluster: "{{ control_plane_kubernetes_cluster_name }}"
      user: "admin"
current-context: default
preferences: {}
users:
  - name: "admin"
    user:
      client-certificate-data: {{ control_plane_admin_user_cert | string | b64encode }}
      client-key-data: {{ control_plane_admin_user_key | string | b64encode }}
