#jinja2: lstrip_blocks: True, trim_blocks: True
---
apiVersion: v1
kind: Pod
metadata:
  name: kube-controller-manager
  namespace: kube-system
#  annotations:
#    seccomp.security.alpha.kubernetes.io/pod: "docker/default"
  labels:
    k8s-app: kube-controller-manager
    tier: control-plane
    component: kube-controller-manager
spec:
  priorityClassName: "system-node-critical"
  priority: 2000001000
  hostNetwork: true
  containers:
    - name: kube-controller-manager
      image: k8s.gcr.io/kube-controller-manager:{{ control_plane_kubernetes_version }}
      command:
        - "/bin/sh"
      args:
        - "-c"
        - "/usr/local/bin/kube-controller-manager"
        - "--authentication-kubeconfig='{{ __control_plane_manifests_kube_controller_manager_kubeconfig_file }}'"
        - "--authorization-kubeconfig='{{ __control_plane_manifests_kube_controller_manager_kubeconfig_file }}'"
        - "--bind-address='0.0.0.0'"
        - "--cluster-cidr='10.200.0.0/16'"
        - "--cluster-name='{{ control_plane_kubernetes_cluster_name }}'"
        - "--cluster-signing-cert-file='{{ __control_plane_pki_ca_cert_file }}'"
        - "--cluster-signing-key-file='{{ __control_plane_pki_ca_key_file }}'"
        - "--kubeconfig='{{ __control_plane_manifests_kube_controller_manager_kubeconfig_file }}'"
        - "--leader-elect='true'"
        - "--log-file='/var/log/kube-controller-manager.log'"
        - "--logtostderr='false'"
        - "--profiling='false'"
        - "--requestheader-client-ca-file='{{ __control_plane_pki_ca_cert_file }}'"
        - "--root-ca-file='{{ __control_plane_pki_ca_cert_file }}'"
        - "--service-account-private-key-file='{{ __control_plane_pki_service_account_key_file }}'"
        - "--service-cluster-ip-range='10.32.0.0/24'"
        - "--tls-cert-file='{{ __control_plane_pki_kube_controller_manager_cert_file }}'"
        - "--tls-min-version='VersionTLS12'"
        - "--tls-private-key-file='{{ __control_plane_pki_kube_controller_manager_key_file }}'"
        - "--use-service-account-credentials='true'"
        - "--v='2'"
      livenessProbe:
        httpGet:
          host: 127.0.0.1
          path: /healthz
          port: 10252
        initialDelaySeconds: 30
        timeoutSeconds: 5
      resources:
        requests:
          cpu: 100m
      volumeMounts:
        - name: "{{ __control_plane_manifests_dir | replace('/', '') }}"
          mountPath: "{{ __control_plane_manifests_dir }}"
          readOnly: true
        - name: "{{ __control_plane_pki_dir | replace('/', '') }}"
          mountPath: "{{ __control_plane_pki_dir }}"
          readOnly: true
        - name: logfile
          mountPath: /var/log/kube-controller-manager.log
  volumes:
    - name: "{{ __control_plane_manifests_dir | replace('/', '') }}"
      hostPath:
        path: "{{ __control_plane_manifests_dir }}"
    - name: "{{ __control_plane_pki_dir | replace('/', '') }}"
      hostPath:
        path: "{{ __control_plane_pki_dir }}"
    - name: logfile
      hostPath:
        path: /var/log/kube-controller-manager.log
        type: "FileOrCreate"